rootNamespace: "default"
replicaCount: 1
image:
  repository: rahulbhiwagade122/desishowbiz
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

env:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: "G-7RS7WCNBHJ"

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Strategy for forcing redeployment
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
