version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile   # Use your production Dockerfile
    container_name: desishowbiz-frontend
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped
