rootNamespace: "default"
image:
  repository: rahulbhiwagade122/desishowbiz
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
  tls: []
